"""create tables

Revision ID: 38580d54cb37
Revises: d16c530aa013
Create Date: 2022-04-14 06:41:52.917640

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '38580d54cb37'
down_revision = 'd16c530aa013'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bbs_thread',
    sa.Column('thread_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('thread_title', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('anime_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('ipaddress', sa.String(length=100), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['anime_id'], ['anime_list.anime_id'], ),
    sa.PrimaryKeyConstraint('thread_id'),
    sa.UniqueConstraint('thread_title')
    )
    op.alter_column('anime_list', 'anime_id',
               existing_type=mysql.INTEGER(),
               nullable='False',
               autoincrement=True)
    op.alter_column('anime_list', 'anime_title',
               existing_type=mysql.VARCHAR(length=100),
               nullable='False')
    op.alter_column('anime_vote', 'vote_id',
               existing_type=mysql.INTEGER(),
               nullable='False',
               autoincrement=True)
    op.alter_column('user', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable='False',
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('anime_vote', 'vote_id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('anime_list', 'anime_title',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('anime_list', 'anime_id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.drop_table('bbs_thread')
    # ### end Alembic commands ###
