"""create tables

Revision ID: aed638331fe5
Revises: 
Create Date: 2022-04-14 09:32:02.372707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aed638331fe5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anime_list',
    sa.Column('anime_id', sa.Integer(), nullable=False),
    sa.Column('anime_title', sa.String(length=100), nullable=False),
    sa.Column('subsc_id_list', sa.String(length=100), nullable=True),
    sa.Column('genre_id_list', sa.String(length=100), nullable=True),
    sa.Column('start_at', sa.DATETIME(), nullable=False),
    sa.Column('end_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('anime_id'),
    sa.UniqueConstraint('anime_title')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('refresh_token', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('anime_vote',
    sa.Column('vote_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('anime_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('ipaddress', sa.String(length=100), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['anime_id'], ['anime_list.anime_id'], ),
    sa.PrimaryKeyConstraint('vote_id')
    )
    op.create_table('bbs_thread',
    sa.Column('thread_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('thread_title', sa.String(length=100), nullable=False),
    sa.Column('anime_id', sa.Integer(), nullable=True),
    sa.Column('tag', sa.String(length=100), nullable=True),
    sa.Column('image', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('ipaddress', sa.String(length=100), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['anime_id'], ['anime_list.anime_id'], ),
    sa.PrimaryKeyConstraint('thread_id'),
    sa.UniqueConstraint('thread_title')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bbs_thread')
    op.drop_table('anime_vote')
    op.drop_table('user')
    op.drop_table('anime_list')
    # ### end Alembic commands ###
