"""create tables

Revision ID: 29aacd7d4309
Revises: 
Create Date: 2022-08-23 00:53:43.259363

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '29aacd7d4309'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('refresh_token', sa.String(length=255), nullable=False),
    sa.Column('is_usage', mysql.TINYINT(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('t_bbs_thread',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('thread_title', sa.String(length=20), nullable=False),
    sa.Column('post_user_id', sa.Integer(), nullable=False),
    sa.Column('post_user_name', sa.String(length=20), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=False),
    sa.Column('is_usage', mysql.TINYINT(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_user_id'], ['t_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thread_title')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_bbs_thread')
    op.drop_table('t_user')
    # ### end Alembic commands ###
